Voting/urls.py
from django.contrib import admin
from django.urls import path
from Vote.view import *
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home,name='home' ),
    path('loginform',Login,name='l' ),
    path('signup', signup, name='k'),
    path('forgot', forgot, name='r'),
    path('how', how, name='h'),
    path('party_detail/<int:pid>', Party_detail, name='pd'),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

Vote/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class User_detail(models.Model):
    usr = models.ForeignKey(User,on_delete = models.CASCADE,null=True)
    name = models.CharField(max_length=100,null=True)
    email = models.EmailField(null=True)
    mobile = models.CharField(max_length=10, null=True)
    aadhar = models.CharField(max_length=12, null=True)
    DOB = models.CharField(max_length=15, null=True)
    id_proof = models.CharField(max_length=100, null=True)
    photo = models.FileField( null=True)
    def __str__(self):
        return self.name

class Party(models.Model):
    party_name = models.CharField(max_length=100, null=True)
    logo = models.FileField(null=True)

    def __str__(self):
        return self.party_name



class Nominance(models.Model):
    party_data =  models.ForeignKey(Party,on_delete = models.CASCADE,null=True)
    nomi_name = models.CharField(max_length=100, null=True)
    image = models.FileField(null=True)
    place = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.party_data.party_name + '-----' + self.nomi_name

Vote/templates/Nominance.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
  
	

     <!-- ==============================================
	 Dashboard Section
	 =============================================== -->
     <div class="featured-users">
	  <div class="container">
	   <div class="row">
			<div class="section-title" style="padding-top: 20px;">
				<h1>Organization :- {{ party.party_name }}</h1>
			</div>
	   
		  <!-- START OF INTERNAL ROW --><div class="row">
	   {% for i in party.nominance_set.all %}
	   <div class="col-lg-4">	
	    <span id="comment458484136448"></span>
				  
         <div class="text-center card-box">
		  <div class="clearfix"></div>
		  <div class="member-card">
		   <div class="thumb-xl member-thumb m-b-10 center-block">
		    <img src="{{ i.image.url }}" class="img-circle img-thumbnail" alt="profile-image">
			<i class="mdi mdi-star-circle member-star text-success" title="verified user"></i>
		   </div>

		   <div class="">
			<h4 class="m-b-5">{{ i.nomi_name }}</h4>
			   <h4 class="m-b-5">Place: {{ i.place }}</h4>
			<p class="text-mint"><span class="text-mint"> {{ i.party_data.party_name }}</span></p>
			</div>

			
		   <a href="../manifesto/458484136448.html" class="kafe-btn kafe-btn-mint-small"><i class="fa fa-user-secret" aria-hidden="true"></i> View Manifesto</a>
		  </div>
		 </div>
	   </div><!-- /.col-lg-4 -->
		   {% endfor %}

					 
	   
	   			 <p>No Content Available.</p>	        </div><!-- /.row -->
	    </div><!-- /.container -->
	</div>	 	 
	 
     <!-- Include footer.php. Contains footer content. -->
 	 
	
	 <!-- ==============================================
	 Footer Section
	 =============================================== -->
	 <footer class="footerWhite">

      <!-- COPY RIGHT -->
      <div class="clearfix copyRight">
       <div class="container">
        <div class="row">
         
		 <div class="col-xs-12">
          <div class="copyRightWrapper">
           <div class="row">
		   
            <div class="col-sm-5 col-sm-push-7 col-xs-12">
			 <ul class="list-inline socialLink">
			  <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
			  <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
			  <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
			  <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
			 </ul>
            </div><!-- /col-sm-5 -->
			
		    <div class="col-sm-7 col-sm-pull-5 col-xs-12">
			 <div class="copyRightText">
			  <p>Copyright © Voting&nbsp; 2018. All Rights Reserved</p>
			 </div>
		    </div><!-- /col-sm-7 -->
		  
           </div><!-- /row -->
          </div><!-- /copyRightWrapper -->
         </div><!-- /col-xs-2 -->

        </div><!-- /row -->
       </div><!-- /container -->
      </div><!-- /copyRight -->
	  
    </footer>	
	
    {% endblock %}

Vote/templates/base.html
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Mirrored from www.themashabrand.com/scripts/Voting/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 30 Sep 2019 22:50:16 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
	{% load static %}

    <!-- Include header.php. Contains header content. -->
         	    <!-- ==============================================
		Title and Meta Tags
		=============================================== -->
		<meta charset="utf-8">
		<title>Voting - Online Voting Platform</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="description" content="Online Voting Platform">
        <meta name="keywords" content="Online Voting Platform, voting ">
        <meta name="author" content="index.html">

		<!-- ==============================================
		Favicons
		=============================================== -->
		<link rel="apple-touch-icon" sizes="57x57" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="114x114" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="72x72" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="144x144" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="60x60" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="120x120" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="76x76" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="152x152" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="180x180" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="icon" type="image/png" href="https://www.duuuunk.com/a-new-beginning" sizes="96x96">
		<link rel="icon" type="image/png" href="https://www.duuuunk.com/a-new-beginning" sizes="16x16">
		<link rel="icon" type="image/png" href="https://www.duuuunk.com/a-new-beginning" sizes="32x32">
		<meta name="msapplication-TileColor" content="#2b5797">
		<meta name="msapplication-TileImage" content="https://www.duuuunk.com/a-new-beginning">

	    <!-- ==============================================
		CSS
		=============================================== -->
        <!-- Style-->
        <link type="text/css" href="{% static 'source/assets/css/style.css' %}" rel="stylesheet" />
     <link type="text/css" href="{% static 'source/assets/css/login.css' %}" rel="stylesheet" />

        <link type="text/css" href="{% static 'source/assets/css/style.css' %}" rel="stylesheet" />

		<!-- ==============================================
		Feauture Detection
		=============================================== -->
		<script src="https://www.duuuunk.com/a-new-beginning"></script>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js' %}"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js' %}"></script>
		<![endif]-->

<script async src="../../../pagead2.googlesyndication.com/pagead/js/f.txt"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-4921714320142871",
          enable_page_level_ads: true
     });
</script>


</head>
<body>

     <!-- Include navigation.php. Contains navigation content. -->

     <!-- ==============================================
     Navigation Section
     =============================================== -->
     <header class="tr-header">
      <nav class="navbar navbar-default">
       <div class="container">
	    <div class="navbar-header">
		 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
		  <span class="sr-only">Toggle navigation</span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		 </button>
		 <a class="navbar-brand" href="{% url 'home' %}">Voting</a>
		</div><!-- /.navbar-header -->
		<div class="navbar-left">
		 <div class="collapse navbar-collapse" id="navbar-collapse">
		  <ul class="nav navbar-nav">
		   <li class="active"><a href="{% url 'home' %}">Home</a></li>
		   <li class=""><a href="{% url 'h' %}">How it works</a></li>
		  </ul>
		 </div>
		</div><!-- /.navbar-left -->
		<div class="navbar-right">

		 <ul class="nav navbar-nav">
              <li class="dropdown user user-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">

                  <!-- hidden-xs hides the username on small devices so only the image appears. -->
                  <span class="hidden-xs">
                  	Languages                  </span>
                </a>
                <ul class="dropdown-menu">
                	<li class="m_2"><a onclick="changelanguage(456316203361)" style="cursor: pointer;">English</a></li><li class="m_2"><a onclick="changelanguage(492663265157)" style="cursor: pointer;">Spanish</a></li>
        		</ul>
              </li>
           </ul>


		 <ul class="nav navbar-nav">

		  <li><i class="fa fa-user"></i></li>
		  <li class=""><a href="{% url 'l' %}">Login</a></li>
		 </ul><!-- /.sign-in -->
		 <a href="{% url 'k' %}" class="kafe-btn kafe-btn-mint-small">
		 	Register		 	as		 	a		 	Voter		 </a>

		</div><!-- /.nav-right -->
       </div><!-- /.container -->
      </nav><!-- /.navbar -->
     </header><!-- Page Header -->

{% block body %}
{% endblock %}

  <a id="scrollup">Scroll</a>


	 <!-- ==============================================
	 Scripts
	 =============================================== -->
     <script src="{% static 'source/assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'source/assets/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'source/assets/js/waypoints.min.js' %}"></script>
	<script src="{% static 'source/assets/js/jquery.easypiechart.min.js' %}"></script>
	<script src="{% static 'source/assets/js/debunk.js' %}"></script>
	<script type="text/javascript">
	    function ajaxfunction(parent)
	    {
	        $.ajax({
			    type: "POST",
	            url: "http://www.themashabrand.com/scripts/Voting/source/admin/template/requests/process.php",
			    data: "parent="+parent,
			    cache: false,
	            success: function(data) {
	                $("#sub").html(data);
	            }
	        });
	    }
	</script>

	 <script>
		/*============================================
		Change Language
		==============================================*/

		function changelanguage(languageid) {
			// id = unique id of the message/comment
			// type = type of post: message/comment

			$.ajax({
				type: "POST",
				url: "http://www.themashabrand.com/scripts/Voting/source/admin/template/requests/changelanguage.php",
				data: "languageid="+languageid,
				cache: false,
				success: function(html) {
					window.location.reload();
				}
			});
		}
	</script>

 	 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','../../../www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-79656468-4', 'auto');
  ga('send', 'pageview');

</script></body>

<!-- Mirrored from www.themashabrand.com/scripts/Voting/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 30 Sep 2019 22:50:45 GMT -->
</html>

Vote/templates/forgot.html
     {% extends 'base.html' %}
{% block body %}
{% load static %}


	  <!-- ==============================================
	 Header
	 =============================================== -->
	 <header class="header-login top-page" style="

  background: url('{% static 'source/admin/uploads/1517252709.jpg' %}') no-repeat center center fixed;
  background-size: cover;
  background-position: center center;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  color: #fff;
  height: 30vh;
  width: 100%;

  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;">
      <div class="container">
	   <div class="content">
	    <div class="row">
	     <h1 class="revealOnScroll" data-animation="fadeInDown"> Voting</h1>
        </div><!-- /.row -->
       </div><!-- /.content -->
	  </div><!-- /.container -->
     </header><!-- /header -->
	 
     <!-- ==============================================
     Banner Login Section
     =============================================== -->
	 <section class="banner-login">
	  <div class="container">
	  		  	
	   <div class="row">
	   
	    <main class="main main-signup col-lg-12">
	     <div class="col-lg-6 col-lg-offset-3 text-center">
		
	        	        
	        	        
		  				
		  <div class="form-sign">
		   <form method="post">
		    <div class="form-head">
			 <h3>Forgot Password?</h3>
			</div><!-- /.form-head -->
            <div class="form-body">          	
             
             <div class="form-row">
			  <div class="form-controls">
			   <input type="text" name="email" class="field" placeholder="Email">
			  </div><!-- /.form-controls -->
             </div><!-- /.form-row -->
		   
			 </div><!-- /.form-body -->
	
			 <div class="form-foot">
			  <div class="form-actions">
               <input type="hidden" name="token" value="c72ca28d7dc01d838a576edc9e4d8b20" />
			   <input type="submit" name="register" value="Forgot Password" class="kafe-btn kafe-btn-default full-width">
			  </div><!-- /.form-actions -->
			 </div><!-- /.form-foot -->
		   </form>
		   
		  </div><!-- /.form-sign -->
	     </div><!-- /.col-lg-6 -->
        </main>
		
	   </div><!-- /.row -->
	  </div><!-- /.container -->
     </section><!-- /section --> 	

	 
     <!-- Include footer.php. Contains footer content. -->
 	 
	
	 <!-- ==============================================
	 Footer Section
	 =============================================== -->
	 <footer class="footerWhite">

      <!-- COPY RIGHT -->
      <div class="clearfix copyRight">
       <div class="container">
        <div class="row">
         
		 <div class="col-xs-12">
          <div class="copyRightWrapper">
           <div class="row">
		   
            <div class="col-sm-5 col-sm-push-7 col-xs-12">
			 <ul class="list-inline socialLink">
			  <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
			  <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
			  <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
			  <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
			 </ul>
            </div><!-- /col-sm-5 -->
			
		    <div class="col-sm-7 col-sm-pull-5 col-xs-12">
			 <div class="copyRightText">
			  <p>Copyright © Voting&nbsp; 2018. All Rights Reserved</p>
			 </div>
		    </div><!-- /col-sm-7 -->
		  
           </div><!-- /row -->
          </div><!-- /copyRightWrapper -->
         </div><!-- /col-xs-2 -->

        </div><!-- /row -->
       </div><!-- /container -->
      </div><!-- /copyRight -->
	  
    </footer>	
	
           {% endblock %}

Vote/templates/how.html
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Mirrored from www.themashabrand.com/scripts/Voting/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 30 Sep 2019 22:50:16 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
	{% load static %}

    <!-- Include header.php. Contains header content. -->
         	    <!-- ==============================================
		Title and Meta Tags
		=============================================== -->
		<meta charset="utf-8">
		<title>Voting - Online Voting Platform</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="description" content="Online Voting Platform">
        <meta name="keywords" content="Online Voting Platform, voting ">
        <meta name="author" content="index.html">

		<!-- ==============================================
		Favicons
		=============================================== -->
		<link rel="apple-touch-icon" sizes="57x57" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="114x114" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="72x72" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="144x144" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="60x60" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="120x120" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="76x76" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="152x152" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="apple-touch-icon" sizes="180x180" href="https://www.duuuunk.com/a-new-beginning">
		<link rel="icon" type="image/png" href="https://www.duuuunk.com/a-new-beginning" sizes="96x96">
		<link rel="icon" type="image/png" href="https://www.duuuunk.com/a-new-beginning" sizes="16x16">
		<link rel="icon" type="image/png" href="https://www.duuuunk.com/a-new-beginning" sizes="32x32">
		<meta name="msapplication-TileColor" content="#2b5797">
		<meta name="msapplication-TileImage" content="https://www.duuuunk.com/a-new-beginning">

	    <!-- ==============================================
		CSS
		=============================================== -->
        <!-- Style-->
      <link type="text/css" href="{% static 'source/assets/css/style.css' %}" rel="stylesheet" />

		<!-- ==============================================
		Feauture Detection
		=============================================== -->
		<script src="https://www.duuuunk.com/a-new-beginning"></script>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js' %}"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js' %}"></script>
		<![endif]-->

<script async src="../../../pagead2.googlesyndication.com/pagead/js/f.txt"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-4921714320142871",
          enable_page_level_ads: true
     });
</script>


</head>
<body>

     <!-- Include navigation.php. Contains navigation content. -->

     <!-- ==============================================
     Navigation Section
     =============================================== -->
     <header class="tr-header">
      <nav class="navbar navbar-default">
       <div class="container">
	    <div class="navbar-header">
		 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
		  <span class="sr-only">Toggle navigation</span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		 </button>
		 <a class="navbar-brand" href="{% url 'home' %}">Voting</a>
		</div><!-- /.navbar-header -->
		<div class="navbar-left">
		 <div class="collapse navbar-collapse" id="navbar-collapse">
		  <ul class="nav navbar-nav">
		   <li class="active"><a href="{% url 'home' %}">Home</a></li>
		   <li class=""><a href="{% url 'h' %}">How it works</a></li>
		  </ul>
		 </div>
		</div><!-- /.navbar-left -->
		<div class="navbar-right">

		 <ul class="nav navbar-nav">
              <li class="dropdown user user-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">

                  <!-- hidden-xs hides the username on small devices so only the image appears. -->
                  <span class="hidden-xs">
                  	Languages                  </span>
                </a>
                <ul class="dropdown-menu">
                	<li class="m_2"><a onclick="changelanguage(456316203361)" style="cursor: pointer;">English</a></li><li class="m_2"><a onclick="changelanguage(492663265157)" style="cursor: pointer;">Spanish</a></li>
        		</ul>
              </li>
           </ul>


		 <ul class="nav navbar-nav">

		  <li><i class="fa fa-user"></i></li>
		  <li class=""><a href="{% url 'l' %}">Login</a></li>
		 </ul><!-- /.sign-in -->
		 <a href="{% url 'k' %}" class="kafe-btn kafe-btn-mint-small">
		 	Register		 	as		 	a		 	Voter		 </a>

		</div><!-- /.nav-right -->
       </div><!-- /.container -->
      </nav><!-- /.navbar -->
     </header><!-- Page Header -->



	

     <!-- ==============================================
	 Dashboard Section
	 =============================================== -->
     <div class="tr-profile section-padding">
	  <div class="container">
	   <div class="row">
	    <div class="col-sm-4 col-md-3">
		 <div class="tr-sidebar">
		  <ul class="nav profile-tabs" role="tablist">
		   <li role="presentation" class="active">
		    <a href="how.html" aria-controls="account-info">
			 <i class="fa fa-life-ring" aria-hidden="true"></i> How it works			</a>
		   </li>
		  </ul>			        			
		 </div><!-- /.tr-sidebar -->        		
	    </div>
	    <div class="col-sm-8 col-md-9">
	     <div class="tab-content">
		 
		  <div role="tabpanel" class="tab-pane fade in active account-info" id="account-info">	
		  
		   <div class="section how-to">
         <h3>How to use this Voting Platform</h3>
       <ul>
        <li> - Admin adds an Organization e.g Harvard Campus Election</li>
        <li> - Admin then adds the Positions in that Organization.</li>
        <li> - Admin then adds Nominees for those Positions</li>
        <li> - Then the Voters vote.</li>
       </ul>
			 
		   </div><!-- /.how-to -->	   
          
		  </div><!-- /.tab-pane -->
						
					</div>
	            </div>
	        </div><!-- /.row -->
	    </div><!-- /.container -->
	</div>	 	 
	 
     <!-- Include footer.php. Contains footer content. -->
 	 
	
	 <!-- ==============================================
	 Footer Section
	 =============================================== -->
	 <footer class="footerWhite">

      <!-- COPY RIGHT -->
      <div class="clearfix copyRight">
       <div class="container">
        <div class="row">
         
		 <div class="col-xs-12">
          <div class="copyRightWrapper">
           <div class="row">
		   
            <div class="col-sm-5 col-sm-push-7 col-xs-12">
			 <ul class="list-inline socialLink">
			  <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
			  <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
			  <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
			  <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
			 </ul>
            </div><!-- /col-sm-5 -->
			
		    <div class="col-sm-7 col-sm-pull-5 col-xs-12">
			 <div class="copyRightText">
			  <p>Copyright © Voting&nbsp; 2018. All Rights Reserved</p>
			 </div>
		    </div><!-- /col-sm-7 -->
		  
           </div><!-- /row -->
          </div><!-- /copyRightWrapper -->
         </div><!-- /col-xs-2 -->

        </div><!-- /row -->
       </div><!-- /container -->
      </div><!-- /copyRight -->
	  
    </footer>	
	
     <a id="scrollup">Scroll</a> 

	 
	 <!-- ==============================================
	 Scripts
	 =============================================== -->
	<script src="source/assets/js/jquery-3.2.1.min.js"></script>
	<script src="source/assets/js/bootstrap.min.js"></script>
	<script src="source/assets/js/debunk.js"></script>
     
	 <script>	
		/*============================================
		Change Language
		==============================================*/
	 
		function changelanguage(languageid) {
			// id = unique id of the message/comment
			// type = type of post: message/comment
	
			$.ajax({
				type: "POST",
				url: "http://www.themashabrand.com/scripts/Voting/source/admin/template/requests/changelanguage.php",
				data: "languageid="+languageid, 
				cache: false,
				success: function(html) {
					window.location.reload();
				}
			});
		}		
	</script>  
 	 
 	 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','../../../www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-79656468-4', 'auto');
  ga('send', 'pageview');

</script> 	 
</body>

<!-- Mirrored from www.themashabrand.com/scripts/Voting//how by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 30 Sep 2019 22:50:50 GMT -->
</html>